const test=require('node:test'),assert=require('node:assert/strict');
const {createFlow,describe,relative}=require('../../DoggyDrop/wwwroot/js/infrastructure-confirmations.js');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function fixture(){const locations=[],requests=[],states=[],successes=[];let current=true;
 const flow=createFlow({locate:()=>{const d=deferred();locations.push(d);return d.promise;},send:(target,position,signal)=>{const d=deferred();requests.push({...d,target,position,signal});return d.promise;},state:(...s)=>states.push(s),current:()=>current,success:(...s)=>successes.push(s)});
 return {flow,locations,requests,states,successes,hide:()=>current=false};}
const tick=()=>Promise.resolve(),point={latitude:46,longitude:15,accuracy:5},ok={outcome:'accepted',summary:{state:'recent',recentUniqueConfirmers:1,lastConfirmedAt:'2026-10-02T12:00:00Z'}};
for(const kind of ['bin','water'])test(`${kind}: immediate busy, duplicate suppression, server-authoritative success`,async()=>{const f=fixture(),target={kind,id:1};const p=f.flow.start(target);assert.equal(f.states[0][1],true);assert.equal(f.states[0][2],'Preverjam lokacijo …');assert.equal(await f.flow.start(target),false);assert.equal(f.locations.length,1);f.locations[0].resolve(point);await tick();assert.equal(f.requests.length,1);f.requests[0].resolve(ok);assert.equal(await p,true);assert.deepEqual(f.successes[0],[target,ok.summary]);assert.equal(f.states.at(-1)[1],false);});
test('closed popup cannot submit after late location callback',async()=>{const f=fixture(),p=f.flow.start({kind:'bin',id:1});f.hide();f.locations[0].resolve(point);await p;assert.equal(f.requests.length,0);});
test('cancelled geolocation cannot confirm popup B as A',async()=>{const f=fixture(),a=f.flow.start({kind:'bin',id:1});f.flow.cancel();const b=f.flow.start({kind:'water',id:2});f.locations[0].resolve(point);await a;assert.equal(f.requests.length,0);f.locations[1].resolve(point);await tick();assert.equal(f.requests[0].target.id,2);f.requests[0].resolve(ok);await b;assert.equal(f.successes.length,1);});
test('cancelled request and late success cannot overwrite new state',async()=>{const f=fixture(),a=f.flow.start({id:1});f.locations[0].resolve(point);await tick();f.flow.cancel();assert.equal(f.requests[0].signal.aborted,true);const b=f.flow.start({id:2});f.locations[1].resolve(point);await tick();f.requests[1].resolve(ok);await b;f.requests[0].resolve(ok);await a;assert.equal(f.successes.length,1);assert.equal(f.successes[0][0].id,2);});
for(const outcome of ['far','accuracy','unavailable','cooldown','busy','login'])test(`${outcome} response resets busy without inventing evidence`,async()=>{const f=fixture(),p=f.flow.start({id:1});f.locations[0].resolve(point);await tick();f.requests[0].resolve({outcome});await p;assert.equal(f.states.at(-1)[1],false);assert.equal(f.successes.length,0);assert.ok(f.states.at(-1)[2]);});
for(const code of [1,2,3])test(`location error ${code} allows retry`,async()=>{const f=fixture(),p=f.flow.start({id:1});f.locations[0].reject({code,location:true});await p;assert.equal(f.states.at(-1)[1],false);const retry=f.flow.start({id:1});assert.equal(f.locations.length,2);f.flow.cancel();f.locations[1].resolve(point);await retry;});
test('network failure allows retry and late error cannot clobber new target',async()=>{const f=fixture(),p=f.flow.start({id:1});f.locations[0].resolve(point);await tick();f.requests[0].reject(Error());await p;assert.equal(f.states.at(-1)[1],false);assert.match(f.states.at(-1)[2],/ne podvoji/);});
test('Slovenian calendar relative dates work across UTC midnight and DST',()=>{const now=Date.parse('2026-10-02T12:00:00Z');assert.equal(relative('2026-10-02T00:00:00Z',now),'danes');assert.equal(relative('2026-10-01T12:00:00Z',now),'včeraj');assert.equal(relative('2026-09-30T12:00:00Z',now),'pred 2 dnevoma');assert.equal(relative('2026-09-29T12:00:00Z',now),'pred 3 dnevi');assert.match(relative('2026-01-01',now),/^dne /);assert.equal(relative(null,now),'');assert.equal(relative('2026-10-24T23:00:00Z',Date.parse('2026-10-25T23:00:00Z')),'včeraj');});
test('source-backed unconfirmed is neutral and issue takes precedence over positive',()=>{assert.match(describe(null,false).primary,/Še ni potrjeno/);const result=describe({...ok.summary,hasCurrentIssue:true},false,Date.parse('2026-10-02T13:00:00Z'));assert.match(result.primary,/Prijavljena je težava/);assert.match(result.secondary,/Prisotnost potrjena/);assert.match(describe(ok.summary,true).primary,/Delovanje/);assert.doesNotMatch(describe(ok.summary,true).primary,/pitno|varno/);});

test('deterministic deadline releases busy state and ignores late location',async()=>{let timeout;const d=deferred(),states=[],sent=[];const flow=createFlow({locate:()=>d.promise,send:(...s)=>sent.push(s),state:(...s)=>states.push(s),current:()=>true,success:()=>assert.fail('late success'),schedule:fn=>{timeout=fn;return 1;},cancelTimer:()=>{}});const pending=flow.start({id:1});timeout();assert.equal(states.at(-1)[1],false);d.resolve(point);await pending;assert.equal(sent.length,0);});
