const {test}=require('node:test');
const assert=require('node:assert/strict');
const {createRequests,validResult}=require('../../DoggyDrop/wwwroot/js/smart-walk.js');
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
function fixture(){const pending=[],success=[],errors=[],busy=[];const requests=createRequests((payload,signal)=>{const d=deferred();pending.push({...d,payload,signal});return d.promise;},{busy:v=>busy.push(v),success:r=>success.push(r),failure:e=>errors.push(e)});return{requests,pending,success,errors,busy};}
test('first submit synchronously enters busy and rapid second submit is ignored',async()=>{const f=fixture(),first=f.requests.run('one');assert.deepEqual(f.busy,[true]);assert.equal(await f.requests.run('two'),false);assert.equal(f.pending.length,1);f.pending[0].resolve('route');await first;assert.deepEqual(f.success,['route']);assert.deepEqual(f.busy,[true,false]);});
test('cancel aborts provider request and late success cannot revive result',async()=>{const f=fixture(),first=f.requests.run('one');f.requests.cancel();assert.equal(f.pending[0].signal.aborted,true);f.pending[0].resolve('late');await first;assert.deepEqual(f.success,[]);assert.equal(f.requests.busy,false);});
test('newer success survives older success',async()=>{const f=fixture(),a=f.requests.run('old');f.requests.cancel();const b=f.requests.run('new');f.pending[1].resolve('new route');await b;f.pending[0].resolve('old route');await a;assert.deepEqual(f.success,['new route']);});
test('late failure cannot overwrite newer success',async()=>{const f=fixture(),a=f.requests.run('old');f.requests.cancel();const b=f.requests.run('new');f.pending[1].resolve('new route');await b;f.pending[0].reject(Error('late'));await a;assert.deepEqual(f.errors,[]);assert.deepEqual(f.success,['new route']);});
test('old completion cannot reenable controls during a newer request',async()=>{const f=fixture(),a=f.requests.run('old');f.requests.cancel();const b=f.requests.run('new');f.pending[0].resolve('old');await a;assert.equal(f.requests.busy,true);assert.equal(f.busy.at(-1),true);f.pending[1].resolve('new');await b;assert.equal(f.requests.busy,false);});
test('network failure restores retry without a second automatic provider call',async()=>{const f=fixture(),a=f.requests.run('one');f.pending[0].reject(Error('offline'));await a;assert.equal(f.requests.busy,false);assert.equal(f.errors.length,1);assert.equal(f.pending.length,1);const b=f.requests.run('retry');f.pending[1].resolve('ok');await b;assert.deepEqual(f.success,['ok']);});
test('render validation failure restores controls',async()=>{let busy;const req=createRequests(async()=>({}),{busy:v=>busy=v,success:()=>{throw Error('bad result');},failure:()=>{}});await req.run({});assert.equal(busy,false);assert.equal(req.busy,false);});
const result={token:'A'.repeat(48),points:[[46,15],[46.001,15.002]],distanceMeters:2250,durationSeconds:1800};
test('provider metrics and explicit zero coordinates are accepted',()=>{assert.equal(validResult(result),true);assert.equal(validResult({...result,points:[[0,0],[0,.01]]}),true);});
for(const [name,change] of Object.entries({token:{token:'guess'},empty:{points:[]},infinite:{points:[[Infinity,15],[46,15]]},bounds:{points:[[91,15],[46,15]]},duration:{durationSeconds:0},distance:{distanceMeters:NaN},oversized:{points:Array(20001).fill([46,15])}}))test('reject malformed route '+name,()=>assert.equal(validResult({...result,...change}),false));
test('historical route may render without a preview token but cannot be saved as a fresh preview',()=>{const saved={...result,token:undefined};assert.equal(validResult(saved,true),true);assert.equal(validResult(saved),false);});
