using System.Text.RegularExpressions;
using Amazon.S3;
using Amazon.S3.Model;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using DoggyDrop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace DoggyDrop.Services;

public sealed record UserMediaAsset(string Kind, string Key);

public static class UserMediaAssets
{
    private const string Extension = @"\.(?:jpg|jpeg|png|webp|gif|heic|heif)";

    public static UserMediaAsset? Resolve(string? url, string? cloud, string? r2Base)
    {
        if (string.IsNullOrEmpty(url) || url.Contains('%') || url.Contains('\\') || url.Contains("/../") || url.Contains("/./")) return null;
        var local = Regex.Match(url, @"^/uploads/((?:profile-images|walks|trashbins)/[a-fA-F0-9]{32}" + Extension + @")$");
        if (local.Success) return new("local", local.Groups[1].Value);
        if (!Uri.TryCreate(url, UriKind.Absolute, out var uri) || uri.Scheme != "https" || !uri.IsDefaultPort ||
            uri.UserInfo.Length != 0 || uri.Query.Length != 0 || uri.Fragment.Length != 0) return null;
        if (!string.IsNullOrEmpty(cloud) && uri.Host == "res.cloudinary.com")
        {
            // Stored originals and the exact delivery transform generated by this application.
            var match = Regex.Match(uri.AbsolutePath, "^/" + Regex.Escape(cloud) +
                @"/image/upload/(?:f_auto,q_auto/)?v[0-9]+/((?:doggydrop-profile-images|doggydrop-walks|doggydrop-trashbins)/[a-zA-Z0-9_-][a-zA-Z0-9_.-]*)" + Extension + "$");
            if (match.Success) return new("cloud", match.Groups[1].Value);
        }
        if (Uri.TryCreate(r2Base?.TrimEnd('/') + "/", UriKind.Absolute, out var root) && root.Scheme == "https" &&
            uri.Authority == root.Authority && uri.AbsolutePath.StartsWith(root.AbsolutePath, StringComparison.Ordinal))
        {
            var key = uri.AbsolutePath[root.AbsolutePath.Length..];
            if (Regex.IsMatch(key, @"^(?:profile-images|dogs|walks|trashbins)/(?:[0-9]{4}/(?:0[1-9]|1[0-2])/[a-fA-F0-9]{32}|(?:optimized|migrated)/[0-9]{4}/(?:0[1-9]|1[0-2])/[a-zA-Z0-9_-]+-[a-fA-F0-9]{32})" + Extension + "$"))
                return new("r2", key);
        }
        return null;
    }

    // Be more conservative with live references than with deletion candidates: delivery
    // transformations, format aliases and query strings must not hide a shared original.
    public static bool References(UserMediaAsset asset, string? reference, string? cloud, string? r2Base)
    {
        if (string.IsNullOrEmpty(reference)) return false;
        if (asset.Kind == "local" && reference.Split('?', '#')[0] == "/uploads/" + asset.Key) return true;
        if (!Uri.TryCreate(reference, UriKind.Absolute, out var uri)) return false;
        var path = Uri.UnescapeDataString(uri.AbsolutePath);
        if (asset.Kind == "local") return path == "/uploads/" + asset.Key;
        if (asset.Kind == "cloud")
            return uri.Host == "res.cloudinary.com" && path.StartsWith("/" + cloud + "/image/upload/", StringComparison.Ordinal) &&
                Regex.IsMatch(path, "/" + Regex.Escape(asset.Key) + @"(?:\.[^/]*)?$");
        return Uri.TryCreate(r2Base?.TrimEnd('/') + "/", UriKind.Absolute, out var root) &&
            uri.Authority == root.Authority && path == root.AbsolutePath + asset.Key;
    }
}

public interface IUserMediaStorage
{
    UserMediaAsset? Resolve(string? url);
    bool References(UserMediaAsset asset, string? url);
    Task DeleteAsync(UserMediaAsset asset);
}

public sealed class UserMediaStorage(IWebHostEnvironment environment, IOptions<CloudflareR2Settings> settings,
    Cloudinary? cloudinary = null, IAmazonS3? r2 = null) : IUserMediaStorage
{
    private string? Cloud => cloudinary?.Api.Account.Cloud;
    private string? R2Base => r2 == null ? null : settings.Value.PublicBaseUrl;
    public UserMediaAsset? Resolve(string? url) => UserMediaAssets.Resolve(url, Cloud, R2Base);
    public bool References(UserMediaAsset asset, string? url) => UserMediaAssets.References(asset, url, Cloud, R2Base);
    public async Task DeleteAsync(UserMediaAsset asset)
    {
        // Revalidate even callers holding an asset object; never trust arbitrary keys.
        var url = asset.Kind switch {
            "local" => "/uploads/" + asset.Key,
            "cloud" => $"https://res.cloudinary.com/{Cloud}/image/upload/v1/{asset.Key}.webp",
            "r2" => R2Base?.TrimEnd('/') + "/" + asset.Key,
            _ => null
        };
        if (Resolve(url) != asset) return;
        if (asset.Kind == "cloud")
        {
            var result = await cloudinary!.DestroyAsync(new DeletionParams(asset.Key));
            if (result.Error != null || result.Result is not ("ok" or "not found")) throw new IOException("Managed media cleanup failed.");
        }
        else if (asset.Kind == "r2")
            await r2!.DeleteObjectAsync(new DeleteObjectRequest { BucketName = settings.Value.BucketName, Key = asset.Key });
        else
        {
            var root = Path.GetFullPath(environment.WebRootPath);
            var path = root;
            foreach (var part in new[] { "uploads" }.Concat(asset.Key.Split('/')))
            {
                if (IsLink(path)) return;
                path = Path.Combine(path, part);
            }
            if (!IsLink(path)) File.Delete(path);
        }
    }
    private static bool IsLink(string path) => (File.Exists(path) || Directory.Exists(path)) &&
        (File.GetAttributes(path) & FileAttributes.ReparsePoint) != 0;
}

public interface IUserMediaCleanup
{
    Task CleanupAsync(IEnumerable<string?> urls);
}

public sealed class UserMediaCleanup(DbContextOptions<ApplicationDbContext> options, IUserMediaStorage storage,
    ILogger<UserMediaCleanup> logger) : IUserMediaCleanup
{
    public async Task CleanupAsync(IEnumerable<string?> urls)
    {
        var assets = urls.Select(storage.Resolve).OfType<UserMediaAsset>().Distinct().ToArray();
        foreach (var asset in assets)
        {
            try
            {
                // A fresh context observes committed references, not stale tracked entities.
                await using var db = new ApplicationDbContext(options);
                var references = db.Users.Select(x => x.ProfileImageUrl)
                    .Concat(db.Dogs.Select(x => x.PhotoUrl)).Concat(db.WalkPhotos.Select(x => (string?)x.ImageUrl))
                    .Concat(db.TrashBins.Select(x => x.ImageUrl)).Concat(db.Places.Select(x => x.ImageUrl))
                    .Concat(db.Places.Select(x => x.LogoUrl))
                    .Concat(db.BinContributions.Where(c => c.Status == DoggyDrop.Models.BinContributionStatus.Pending).Select(c => c.ProposedPhotoUrl));
                var inUse = false;
                await foreach (var url in references.AsAsyncEnumerable())
                    if (storage.References(asset, url)) { inUse = true; break; }
                if (!inUse) await storage.DeleteAsync(asset);
            }
            catch (Exception)
            {
                // Provider exception messages/URLs may contain personal information or credentials.
                logger.LogWarning("Managed media cleanup deferred; backend {Backend}.", asset.Kind);
            }
        }
    }
}
